[variables]
NODE_VERSION = "20.19.0"

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run preview --host 0.0.0.0 --port $PORT"